[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "human_browser"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "playwright",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["human_browser*"]
